### ISSUE TITLE
Nyeste versjon lager ipykernel feilmelding

### ISSUE THREAD

**Issue by EdvardGarmannslund** [statisticsnorway/ssb-pypitemplate#56]
Hei, 

Når jeg bruker nyeste versjon får jeg ipykernel feilmelding fra ssb-project. Det fungerer fint med versjonen fra 2023.11.15. Har ikke testet med de imellom. 
![image](https://github.com/statisticsnorway/ssb-pypitemplate/assets/132445493/54d78d94-1fb4-4bdf-8730-f053e51f5694)

**Comment by EdvardGarmannslund** [comment]
Her er bilder fra versjon 2023.11.15
![image](https://github.com/statisticsnorway/ssb-pypitemplate/assets/132445493/b0fdfca8-70bc-4d31-8d1a-4c4e6f6bbeb5)

**Comment by arneso-ssb** [comment]
@EdvardGarmannslund Bruk `--no-kernel`-opsjonen til `ssb-project` når du oppretter en instans av malen, slik som beskrevet på [SSB-siden om malen](https://statistics-norway.atlassian.net/wiki/spaces/BEST/pages/3574530261/Hvordan+lage+et+python-bibliotek+etter+SSB+standard#Opprett-lokal-instans-av-mal). Da slipper du feilmeldingen.

Malen i seg selv har ingen avhengigheter til ipykernel eller jupyter, men jeg la opprinnelig inn en avhengighet til ipykernel for at man skulle kunne bruke `ssb-project` på malen uten å få feilmelding. Nå som `ssb-project` har fått støtte for `--no-kernel`-opsjonen, så har jeg fjernet denne avhengigheten i nyere versjoner av malen.
